.\"        Title: create-project
.\"       Author: Dean Wampler
.\"         Date: 12/22/2012
.\"
.TH "CREATE-PROJECT" "1" "12/22/2012" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
\fBcreate-project\fR - Create a new \fBStampede\fR project. It will prompt you for information.
.SH "SYNOPSIS"
\fBcreate-project\fR
.sp
.SH "DESCRIPTION"
The create-project(1) command prompts you for project information, such as the name and directory location, then creates the directory and writes "starter" files to it.
.sp
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success if the directory can be created and the files can be written to it.
.RE
.PP
\fB1\fR
.RS 4
Failure if directory can't be created or the files can't be written to it.
.RE
.sp
.SH "AUTHOR"
Written by Dean Wampler, <dean.wampler@thinkbiganalytics.com>
.sp
.SH "RESOURCES"
Main web site: https://github.com/ThinkBigAnalytics/stampede.
.sp
.SH "COPYING"
Copyright (c) 2011\-2013, Think Big Analytics, Inc. Free use of this software is granted under the terms of the Apache License, Version 2.0.
.sp
