.\"        Title: install
.\"       Author: Dean Wampler
.\"         Date: 12/22/2012
.\"
.TH "INSTALL" "1" "12/22/2012" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
\fBinstall\fR - Install Stampede. It will prompt you for information.
.SH "SYNOPSIS"
\fBinstall\fR [\fI--help\fR]
.sp
.SH "DESCRIPTION"
The install(1) command prompts you for a directory to install \fIStampede\fR and 
optionally for a system directory to install a global \fIstampederc\fR file.
.sp
.SH "OPTIONS"
.PP
\fB--help\fR
.RS 4
Show this help message.
.sp
.SH "EXIT STATUS"
.PP
\fB0\fR
.RS 4
Success if no errors occur, such as an unwritable installation directory
.RE
.PP
\fB1\fR
.RS 4
Failure if the installation directory is unwritable, etc.
.RE
.sp
.SH "AUTHOR"
Dean Wampler, <dean.wampler@thinkbiganalytics.com>.
.sp
.SH "RESOURCES"
.sp
See also the tests of this script in \fI$STAMPEDE_HOME/test/test-install.sh\fR for examples.
.sp
Main web site: https://github.com/ThinkBigAnalytics/stampede.
.sp
.SH "COPYING"
Copyright (c) 2011\-2013, Think Big Analytics, Inc. Free use of this software is 
granted under the terms of the Apache License, Version 2.0.
